### ISSUE TITLE
folder structure 

### ISSUE THREAD

**Issue by Shakib-IO** [rohan1198/Leukemia-Classification-using-Deep-Learning#1]
Can you please share the folder structure of the dataset?
Thank you.

**Comment by rohan1198** [comment]
I did some preprocessing on the dataset before starting the python code.
I appended "all" to all the image filenames in the "ALL" directory, and appended "hem" to all the image filenames in "HEM".
Then, I combined the directories into Train and Test.

So essentially, the folder structure is:
Train -> - all.UID_2_28_1_all.bmp
             - hem.UID_H14_15_10_hem.bmp
             - ...

Test  -> - all.UID_2_28_1_all.bmp
             - hem.UID_H14_15_10_hem.bmp
             - ...

I suppose there are much easier and better ways to do this, but this is how I did it at the time.
